"""init db

Revision ID: 011467061260
Revises: 0da5b71b2222
Create Date: 2022-11-07 12:30:59.201166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011467061260'
down_revision = '0da5b71b2222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumno', sa.Column('apedillo_1', sa.String(), nullable=True))
    op.add_column('alumno', sa.Column('apedillo_2', sa.String(), nullable=True))
    op.drop_index('ix_alumno_apedillo1', table_name='alumno')
    op.drop_index('ix_alumno_apedillo2', table_name='alumno')
    op.create_index(op.f('ix_alumno_apedillo_1'), 'alumno', ['apedillo_1'], unique=False)
    op.create_index(op.f('ix_alumno_apedillo_2'), 'alumno', ['apedillo_2'], unique=False)
    op.drop_column('alumno', 'apedillo1')
    op.drop_column('alumno', 'apedillo2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumno', sa.Column('apedillo2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('alumno', sa.Column('apedillo1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_alumno_apedillo_2'), table_name='alumno')
    op.drop_index(op.f('ix_alumno_apedillo_1'), table_name='alumno')
    op.create_index('ix_alumno_apedillo2', 'alumno', ['apedillo2'], unique=False)
    op.create_index('ix_alumno_apedillo1', 'alumno', ['apedillo1'], unique=False)
    op.drop_column('alumno', 'apedillo_2')
    op.drop_column('alumno', 'apedillo_1')
    # ### end Alembic commands ###
