"""init db

Revision ID: 03a6a33c1adf
Revises: a4236e176c05
Create Date: 2022-11-09 20:17:11.497835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03a6a33c1adf'
down_revision = 'a4236e176c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Alumno_id', sa.Integer(), nullable=True),
    sa.Column('Asignatura_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['Asignatura_id'], ['asignatura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mat_id'), 'mat', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mat_id'), table_name='mat')
    op.drop_table('mat')
    # ### end Alembic commands ###
