"""init db

Revision ID: 0850747c391e
Revises: 64c93cc267c2
Create Date: 2022-11-09 21:17:45.036712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0850747c391e'
down_revision = '64c93cc267c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
