"""init db

Revision ID: 0a0d700940a9
Revises: e8b7e9fddfff
Create Date: 2022-11-10 10:24:39.923384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0d700940a9'
down_revision = 'e8b7e9fddfff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
