"""init db

Revision ID: 0da5b71b2222
Revises: f0242b4866bf
Create Date: 2022-11-07 11:30:12.513067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da5b71b2222'
down_revision = 'f0242b4866bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apedillo1', sa.String(), nullable=True),
    sa.Column('apedillo2', sa.String(), nullable=True),
    sa.Column('edad', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumno_apedillo1'), 'alumno', ['apedillo1'], unique=False)
    op.create_index(op.f('ix_alumno_apedillo2'), 'alumno', ['apedillo2'], unique=False)
    op.create_index(op.f('ix_alumno_edad'), 'alumno', ['edad'], unique=False)
    op.create_index(op.f('ix_alumno_email'), 'alumno', ['email'], unique=True)
    op.create_index(op.f('ix_alumno_id'), 'alumno', ['id'], unique=False)
    op.create_index(op.f('ix_alumno_nombre'), 'alumno', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alumno_nombre'), table_name='alumno')
    op.drop_index(op.f('ix_alumno_id'), table_name='alumno')
    op.drop_index(op.f('ix_alumno_email'), table_name='alumno')
    op.drop_index(op.f('ix_alumno_edad'), table_name='alumno')
    op.drop_index(op.f('ix_alumno_apedillo2'), table_name='alumno')
    op.drop_index(op.f('ix_alumno_apedillo1'), table_name='alumno')
    op.drop_table('alumno')
    # ### end Alembic commands ###
