"""init db

Revision ID: 2f8d9b4206a8
Revises: 0a0d700940a9
Create Date: 2022-11-10 10:50:19.450140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8d9b4206a8'
down_revision = '0a0d700940a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
