"""init db

Revision ID: 313ced7cddc1
Revises: 0850747c391e
Create Date: 2022-11-09 21:55:49.742065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313ced7cddc1'
down_revision = '0850747c391e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
