"""init db

Revision ID: 364e8f7260b2
Revises: 2f8d9b4206a8
Create Date: 2022-11-10 10:53:22.699982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364e8f7260b2'
down_revision = '2f8d9b4206a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ensena',
    sa.Column('Asignatura_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Asignatura_id'], ['asignatura.id'], ),
    sa.PrimaryKeyConstraint('Asignatura_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ensena')
    # ### end Alembic commands ###
