"""init db

Revision ID: 64c93cc267c2
Revises: 8d3af3faa1f9
Create Date: 2022-11-09 21:11:24.890543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c93cc267c2'
down_revision = '8d3af3faa1f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_matricula_id', table_name='matricula')
    op.drop_column('matricula', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matricula', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_matricula_id', 'matricula', ['id'], unique=False)
    # ### end Alembic commands ###
