"""init db

Revision ID: 6e31cb5e33a4
Revises: 364e8f7260b2
Create Date: 2022-11-10 10:54:42.298365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e31cb5e33a4'
down_revision = '364e8f7260b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ensena', sa.Column('asignatura_id', sa.Integer(), nullable=False))
    op.drop_constraint('ensena_Asignatura_id_fkey', 'ensena', type_='foreignkey')
    op.create_foreign_key(None, 'ensena', 'asignatura', ['asignatura_id'], ['id'])
    op.drop_column('ensena', 'Asignatura_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ensena', sa.Column('Asignatura_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ensena', type_='foreignkey')
    op.create_foreign_key('ensena_Asignatura_id_fkey', 'ensena', 'asignatura', ['Asignatura_id'], ['id'])
    op.drop_column('ensena', 'asignatura_id')
    # ### end Alembic commands ###
