"""init db

Revision ID: 8d3af3faa1f9
Revises: 03a6a33c1adf
Create Date: 2022-11-09 20:25:51.728559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3af3faa1f9'
down_revision = '03a6a33c1adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matricula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Alumno_id', sa.Integer(), nullable=False),
    sa.Column('Asignatura_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['Asignatura_id'], ['asignatura.id'], ),
    sa.PrimaryKeyConstraint('id', 'Alumno_id', 'Asignatura_id')
    )
    op.create_index(op.f('ix_matricula_id'), 'matricula', ['id'], unique=False)
    op.drop_index('ix_mat_id', table_name='mat')
    op.drop_table('mat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mat',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Alumno_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Asignatura_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Alumno_id'], ['alumno.id'], name='mat_Alumno_id_fkey'),
    sa.ForeignKeyConstraint(['Asignatura_id'], ['asignatura.id'], name='mat_Asignatura_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='mat_pkey')
    )
    op.create_index('ix_mat_id', 'mat', ['id'], unique=False)
    op.drop_index(op.f('ix_matricula_id'), table_name='matricula')
    op.drop_table('matricula')
    # ### end Alembic commands ###
