"""init db

Revision ID: 9d52767ca6f5
Revises: eb5095f44e3d
Create Date: 2022-11-09 22:12:06.747806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d52767ca6f5'
down_revision = 'eb5095f44e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
