"""init db

Revision ID: b1457b83c6a1
Revises: de954b5be8ec
Create Date: 2022-11-14 17:54:20.036299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1457b83c6a1'
down_revision = 'de954b5be8ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
