"""init db

Revision ID: cc0263a95df0
Revises: 011467061260
Create Date: 2022-11-08 11:12:39.082261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0263a95df0'
down_revision = '011467061260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_asignatura', sa.String(), nullable=True),
    sa.Column('profesor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignatura_id'), 'asignatura', ['id'], unique=False)
    op.create_index(op.f('ix_asignatura_nombre_asignatura'), 'asignatura', ['nombre_asignatura'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asignatura_nombre_asignatura'), table_name='asignatura')
    op.drop_index(op.f('ix_asignatura_id'), table_name='asignatura')
    op.drop_table('asignatura')
    # ### end Alembic commands ###
