"""init db

Revision ID: d6c8298bbfcb
Revises: 6e31cb5e33a4
Create Date: 2022-11-14 17:26:16.387672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c8298bbfcb'
down_revision = '6e31cb5e33a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
