"""init db

Revision ID: de954b5be8ec
Revises: d6c8298bbfcb
Create Date: 2022-11-14 17:49:50.940979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de954b5be8ec'
down_revision = 'd6c8298bbfcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
