"""init db

Revision ID: e8b7e9fddfff
Revises: 2eca393e2de4
Create Date: 2022-11-08 12:15:33.710675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b7e9fddfff'
down_revision = '2eca393e2de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('asignatura_profesor_id_fkey', 'asignatura', type_='foreignkey')
    op.drop_column('asignatura', 'profesor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignatura', sa.Column('profesor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('asignatura_profesor_id_fkey', 'asignatura', 'profesor', ['profesor_id'], ['id'])
    # ### end Alembic commands ###
