"""init db

Revision ID: eb5095f44e3d
Revises: 313ced7cddc1
Create Date: 2022-11-09 22:07:42.745378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb5095f44e3d'
down_revision = '313ced7cddc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ensena',
    sa.Column('Profesor_id', sa.Integer(), nullable=False),
    sa.Column('Asignatura_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Asignatura_id'], ['asignatura.id'], ),
    sa.ForeignKeyConstraint(['Profesor_id'], ['profesor.id'], ),
    sa.PrimaryKeyConstraint('Profesor_id', 'Asignatura_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ensena')
    # ### end Alembic commands ###
